apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-teste
  namespace: jenkins-teste
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: jenkins-teste-metadata-filter
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - namespaces
  - services
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jenkins-teste
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-teste-metadata-filter
subjects:
- kind: ServiceAccount
  name: jenkins-teste
  namespace: jenkins-teste